name: framework-nightly-build

on: 
  push:
    branches: 
      - master
  schedule:
    - cron: '0 23 * * *'
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: docker login
      run: |
        docker login -u ${{ secrets.name }} -p ${{ secrets.pass }} 
        # docker login docker.tarsyun.com -u ${{ secrets.tarsname }} -p ${{ secrets.tarspass }} 
    - name: get docker file
      run: git clone https://github.com/TarsCloud/TarsDocker
    - name: Build framework image
      run: cd TarsDocker && docker build ./framework/ --file ./framework/Dockerfile --tag tarscloud/framework:nightly      
    - name: docker push framework
      run: |
        docker push tarscloud/framework:nightly
    - name: Build tars image
      run: cd TarsDocker && docker build ./tars/ --file ./tars/Dockerfile --tag tarscloud/tars:nightly
    - name: docker push tars
      run: |
        docker push tarscloud/tars:nightly
